name: BedWars
version: 2.3
api: [2.0.0, 3.0.0, 3.0.0-ALPHA10]
main: GPlug\BedWars
author: 
 - Bluplayz
 - MrKiAN
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [BW-PM]
    Start:
        description: Bedwars Forcestart Command
